// src/tarotData.js

export const majorArcana = [
  { id: 0, name: "El Loco", image: "https://upload.wikimedia.org/wikipedia/commons/9/90/RWS_Tarot_00_Fool.jpg",
    desc: "Espontáneo, vive el momento, despreocupado, a veces inmaduro o irresponsable. Alguien que se lanza sin red y evita el compromiso a largo plazo.",
   },
  { id: 1, name: "El Mago", image: "https://upload.wikimedia.org/wikipedia/commons/d/de/RWS_Tarot_01_Magician.jpg",
    desc:"Carismático, ingenioso y persuasivo. Sabe vender sus ideas. Puede ser un gran emprendedor o, en su sombra, un manipulador astuto.",
   },
  { id: 2, name: "La Sacerdotisa", image: "https://upload.wikimedia.org/wikipedia/commons/8/88/RWS_Tarot_02_High_Priestess.jpg",
    desc:"Intuitiva, reservada y profunda. No revela todo lo que sabe. Una persona que escucha más de lo que habla y confía en sus corazonadas más que en la lógica.",
   },
  { id: 3, name: "La Emperatriz", image: "https://upload.wikimedia.org/wikipedia/commons/d/d2/RWS_Tarot_03_Empress.jpg",
    desc:"Sensual, cariñosa y protectora. Amante de la belleza, el confort y la naturaleza. Alguien que cuida a los demás, a veces en exceso.",
   },
  { id: 4, name: "El Emperador", image: "https://upload.wikimedia.org/wikipedia/commons/c/c3/RWS_Tarot_04_Emperor.jpg",
    desc:"Autoritario, lógico, disciplinado y protector. Necesita tener el control y establecer reglas. Es el pilar de estabilidad, pero puede ser rígido o inflexible.",
   },
  { id: 5, name: "El Sumo Sacerdote", image: "https://upload.wikimedia.org/wikipedia/commons/8/8d/RWS_Tarot_05_Hierophant.jpg",
    desc:"Conservador, respetuoso de las normas y leal al grupo. Le gusta enseñar y aconsejar. Valora la pertenencia a instituciones y prefiere lo convencional a lo experimental.",
   },
  { id: 6, name: "Los Enamorados", image: "https://upload.wikimedia.org/wikipedia/commons/3/3a/RWS_TheLovers.jpg",
    desc:"Indeciso pero encantador. Busca armonía y conexión profunda. Define su identidad a través de sus relaciones y valores. A veces duda demasiado ante las opciones."
   },
  { id: 7, name: "El Carro", image: "https://upload.wikimedia.org/wikipedia/commons/9/9b/RWS_Tarot_07_Chariot.jpg",
    desc:"Competitivo, enfocado en el éxito y con gran fuerza de voluntad. Alguien que no deja que las emociones le frenen. Puede ser agresivo si se le bloquea.",
   },
  { id: 8, name: "La Fuerza", image: "https://upload.wikimedia.org/wikipedia/commons/f/f5/RWS_Tarot_08_Strength.jpg",
    desc:"Racional, honesto y directo. Valora la verdad por encima de los sentimientos. Puede parecer frío o distante, pero es muy ético.",
   },
  { id: 9, name: "El Ermitaño", image: "https://upload.wikimedia.org/wikipedia/commons/4/4d/RWS_Tarot_09_Hermit.jpg",
    desc:"Introvertido, prudente y sabio. Prefiere la soledad para recargar energía. No le interesan las frivolidades sociales; busca profundidad y autenticidad.",
   },
  { id: 10, name: "La Rueda de la Fortuna", image: "https://upload.wikimedia.org/wikipedia/commons/3/3c/RWS_Tarot_10_Wheel_of_Fortune.jpg",
    desc:"Una persona cambiante, optimista y que se deja llevar por la corriente. Sabe aprovechar las oportunidades, pero a veces le falta consistencia o deja demasiado al azar.",
   },
  { id: 11, name: "La Justicia", image: "https://upload.wikimedia.org/wikipedia/commons/e/e0/RWS_Tarot_11_Justice.jpg",
    desc:"Paciente, compasivo y con gran dominio emocional. Logra sus objetivos con suavidad. No se deja provocar fácilmente.",
   },
  { id: 12, name: "El Colgado", image: "https://upload.wikimedia.org/wikipedia/commons/2/2b/RWS_Tarot_12_Hanged_Man.jpg",
    desc:"Ve la vida desde un ángulo diferente. Dispuesto a pausar sus deseos por otros. Puede parecer pasivo pero es profundamente reflexivo.",
   },
  { id: 13, name: "La Muerte", image: "https://upload.wikimedia.org/wikipedia/commons/d/d7/RWS_Tarot_13_Death.jpg",
    desc:"Intenso, cortante y directo. No tiene miedo a cerrar ciclos o cambiar de piel. Alguien que elimina lo superfluo de su vida sin mirar atrás.",
   },
  { id: 14, name: "La Templanza", image: "https://upload.wikimedia.org/wikipedia/commons/f/f8/RWS_Tarot_14_Temperance.jpg",
    desc:"Tranquilo, paciente y moderado. Busca el punto medio y evita los extremos. Es el pacificador del grupo, alguien que fluye y se adapta.",
   },
  { id: 15, name: "El Diablo", image: "https://upload.wikimedia.org/wikipedia/commons/5/55/RWS_Tarot_15_Devil.jpg",
    desc:"Intenso, seductor y obsesivo. Disfruta de los placeres terrenales y puede tener una personalidad adictiva o controladora, pero con mucho magnetismo.",
   },
  { id: 16, name: "La Torre", image: "https://upload.wikimedia.org/wikipedia/commons/5/53/RWS_Tarot_16_Tower.jpg",
    desc:"Impredecible y directo. Alguien que rompe esquemas y dice verdades incómodas. Puede ser caótico o vivir crisis frecuentes.",
   },
  { id: 17, name: "La Estrella", image: "https://upload.wikimedia.org/wikipedia/commons/d/db/RWS_Tarot_17_Star.jpg",
    desc:"Lleno de fe, inspirador y transparente. Alguien que siempre ve el vaso medio lleno y transmite paz. Puede ser un poco ingenuo o idealista.",
   },
  { id: 18, name: "La Luna", image: "https://upload.wikimedia.org/wikipedia/commons/7/7f/RWS_Tarot_18_Moon.jpg",
    desc:"Emocional, soñador y a veces confuso o inseguro. Tiene una vida interior muy rica, pero puede sufrir ansiedad o proyectar miedos irreales. Muy empático.",
   },
  { id: 19, name: "El Sol", image: "https://upload.wikimedia.org/wikipedia/commons/1/17/RWS_Tarot_19_Sun.jpg",
    desc:"Extrovertido, vital, seguro de sí mismo y alegre. Le gusta ser el centro de atención. Transmite calor y energía, no tiene nada que ocultar.",
   },
  { id: 20, name: "El Juicio", image: "https://upload.wikimedia.org/wikipedia/commons/d/dd/RWS_Tarot_20_Judgement.jpg",
    desc:"Alguien que ha tenido una epifanía o cambio de vida radical. Evalúa a los demás y a sí mismo con rigor. Siente que tiene una misión o vocación importante.",
   },
  { id: 21, name: "El Mundo", image: "https://upload.wikimedia.org/wikipedia/commons/f/ff/RWS_Tarot_21_World.jpg",
    desc:"Completo, maduro y con visión global. Se siente en casa en cualquier lugar. Alguien que termina lo que empieza y tiene una personalidad integrada y satisfecha.",
   },
];